[package]
name = "bitset"
version = "0.1.0"
authors = ["Szymon Lipiński <mabewlun@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
typenum="1.12.0"
num="0.3.0"
generic-array="0.14.3"
